// GENERATED BY scripts/prepare-images.mjs. Do not edit by hand.
// Re-run `node scripts/prepare-images.mjs` after adding photos.
import type { StaticImageData } from "next/image";

import designDoors01 from "@/images/doors/design-doors/design-doors-01.jpg";
import designDoors02 from "@/images/doors/design-doors/design-doors-02.jpg";
import designDoors03 from "@/images/doors/design-doors/design-doors-03.jpg";
import designDoors04 from "@/images/doors/design-doors/design-doors-04.jpg";
import designDoors05 from "@/images/doors/design-doors/design-doors-05.jpg";
import designDoors06 from "@/images/doors/design-doors/design-doors-06.jpg";
import designDoors07 from "@/images/doors/design-doors/design-doors-07.jpg";
import diamondDoors01 from "@/images/doors/diamond-doors/diamond-doors-01.jpg";
import diamondDoors02 from "@/images/doors/diamond-doors/diamond-doors-02.jpg";
import diamondDoors03 from "@/images/doors/diamond-doors/diamond-doors-03.jpg";
import diamondDoors04 from "@/images/doors/diamond-doors/diamond-doors-04.jpg";
import diamondDoors05 from "@/images/doors/diamond-doors/diamond-doors-05.jpg";
import diamondDoors06 from "@/images/doors/diamond-doors/diamond-doors-06.jpg";
import diamondDoors07 from "@/images/doors/diamond-doors/diamond-doors-07.jpg";
import diamondDoors08 from "@/images/doors/diamond-doors/diamond-doors-08.jpg";
import doubleDoors01 from "@/images/doors/double-doors/double-doors-01.jpg";
import perforatedMesh01 from "@/images/doors/perforated-mesh/perforated-mesh-01.jpg";
import perforatedMesh02 from "@/images/doors/perforated-mesh/perforated-mesh-02.jpg";
import perforatedMesh03 from "@/images/doors/perforated-mesh/perforated-mesh-03.jpg";
import privacyMeshDoors01 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-01.jpg";
import privacyMeshDoors02 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-02.jpg";
import privacyMeshDoors03 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-03.jpg";
import privacyMeshDoors04 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-04.jpg";
import privacyMeshDoors05 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-05.jpg";
import privacyMeshDoors06 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-06.jpg";
import privacyMeshDoors07 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-07.jpg";
import privacyMeshDoors08 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-08.jpg";
import privacyMeshDoors09 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-09.jpg";
import privacyMeshDoors10 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-10.jpg";
import privacyMeshDoors11 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-11.jpg";
import privacyMeshDoors12 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-12.jpg";
import privacyMeshDoors13 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-13.jpg";
import privacyMeshDoors14 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-14.jpg";
import privacyMeshDoors15 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-15.jpg";
import privacyMeshDoors16 from "@/images/doors/privacy-mesh-doors/privacy-mesh-doors-16.jpg";
import rollerShutters01 from "@/images/doors/roller-shutters/roller-shutters-01.jpg";
import rollerShutters02 from "@/images/doors/roller-shutters/roller-shutters-02.jpg";
import rollerShutters03 from "@/images/doors/roller-shutters/roller-shutters-03.jpg";
import rollerShutters04 from "@/images/doors/roller-shutters/roller-shutters-04.jpg";
import rollerShutters05 from "@/images/doors/roller-shutters/roller-shutters-05.jpg";
import rollerShutters06 from "@/images/doors/roller-shutters/roller-shutters-06.jpg";
import rollerShutters07 from "@/images/doors/roller-shutters/roller-shutters-07.jpg";
import rollerShutters08 from "@/images/doors/roller-shutters/roller-shutters-08.jpg";
import rollerShutters09 from "@/images/doors/roller-shutters/roller-shutters-09.jpg";
import rollerShutters10 from "@/images/doors/roller-shutters/roller-shutters-10.jpg";
import rollerShutters11 from "@/images/doors/roller-shutters/roller-shutters-11.jpg";
import rollerShutters12 from "@/images/doors/roller-shutters/roller-shutters-12.jpg";
import rollerShutters13 from "@/images/doors/roller-shutters/roller-shutters-13.jpg";
import rollerShutters14 from "@/images/doors/roller-shutters/roller-shutters-14.jpg";
import rollerShutters15 from "@/images/doors/roller-shutters/roller-shutters-15.jpg";
import rollerShutters16 from "@/images/doors/roller-shutters/roller-shutters-16.jpg";
import rollerShutters17 from "@/images/doors/roller-shutters/roller-shutters-17.jpg";
import rollerShutters18 from "@/images/doors/roller-shutters/roller-shutters-18.jpg";
import rollerShutters19 from "@/images/doors/roller-shutters/roller-shutters-19.jpg";
import rollerShutters20 from "@/images/doors/roller-shutters/roller-shutters-20.jpg";
import rollerShutters21 from "@/images/doors/roller-shutters/roller-shutters-21.jpg";
import rollerShutters22 from "@/images/doors/roller-shutters/roller-shutters-22.jpg";
import rollerShutters23 from "@/images/doors/roller-shutters/roller-shutters-23.jpg";
import rollerShutters24 from "@/images/doors/roller-shutters/roller-shutters-24.jpg";
import rollerShutters25 from "@/images/doors/roller-shutters/roller-shutters-25.jpg";
import rollerShutters26 from "@/images/doors/roller-shutters/roller-shutters-26.jpg";
import rollerShutters27 from "@/images/doors/roller-shutters/roller-shutters-27.jpg";
import rollerShutters28 from "@/images/doors/roller-shutters/roller-shutters-28.jpg";
import rollerShutters29 from "@/images/doors/roller-shutters/roller-shutters-29.jpg";
import rollerShutters30 from "@/images/doors/roller-shutters/roller-shutters-30.jpg";
import rollerShutters31 from "@/images/doors/roller-shutters/roller-shutters-31.jpg";
import rollerShutters32 from "@/images/doors/roller-shutters/roller-shutters-32.jpg";
import rollerShutters33 from "@/images/doors/roller-shutters/roller-shutters-33.jpg";
import rollerShutters34 from "@/images/doors/roller-shutters/roller-shutters-34.jpg";
import rollerShutters35 from "@/images/doors/roller-shutters/roller-shutters-35.jpg";
import rollerShutters36 from "@/images/doors/roller-shutters/roller-shutters-36.jpg";
import rollerShutters37 from "@/images/doors/roller-shutters/roller-shutters-37.jpg";
import rollerShutters38 from "@/images/doors/roller-shutters/roller-shutters-38.jpg";
import rollerShutters39 from "@/images/doors/roller-shutters/roller-shutters-39.jpg";
import rollerShutters40 from "@/images/doors/roller-shutters/roller-shutters-40.jpg";
import rollerShutters41 from "@/images/doors/roller-shutters/roller-shutters-41.jpg";
import rollerShutters42 from "@/images/doors/roller-shutters/roller-shutters-42.jpg";
import rollerShutters43 from "@/images/doors/roller-shutters/roller-shutters-43.jpg";
import rollerShutters44 from "@/images/doors/roller-shutters/roller-shutters-44.jpg";
import slidingDoors01 from "@/images/doors/sliding-doors/sliding-doors-01.jpg";
import slidingDoors02 from "@/images/doors/sliding-doors/sliding-doors-02.jpg";
import slidingDoors03 from "@/images/doors/sliding-doors/sliding-doors-03.jpg";
import slidingDoors04 from "@/images/doors/sliding-doors/sliding-doors-04.jpg";
import slidingDoors05 from "@/images/doors/sliding-doors/sliding-doors-05.jpg";
import slidingDoors06 from "@/images/doors/sliding-doors/sliding-doors-06.jpg";
import slidingDoors07 from "@/images/doors/sliding-doors/sliding-doors-07.jpg";
import slidingDoors08 from "@/images/doors/sliding-doors/sliding-doors-08.jpg";
import slidingDoors09 from "@/images/doors/sliding-doors/sliding-doors-09.jpg";
import slidingDoors10 from "@/images/doors/sliding-doors/sliding-doors-10.jpg";
import slidingDoors11 from "@/images/doors/sliding-doors/sliding-doors-11.jpg";
import slidingDoors12 from "@/images/doors/sliding-doors/sliding-doors-12.jpg";
import slidingDoors13 from "@/images/doors/sliding-doors/sliding-doors-13.jpg";
import slidingDoors14 from "@/images/doors/sliding-doors/sliding-doors-14.jpg";
import slidingDoors15 from "@/images/doors/sliding-doors/sliding-doors-15.jpg";
import slidingDoors16 from "@/images/doors/sliding-doors/sliding-doors-16.jpg";
import slidingDoors17 from "@/images/doors/sliding-doors/sliding-doors-17.jpg";
import slidingDoors18 from "@/images/doors/sliding-doors/sliding-doors-18.jpg";
import slidingDoors19 from "@/images/doors/sliding-doors/sliding-doors-19.jpg";
import slidingDoors20 from "@/images/doors/sliding-doors/sliding-doors-20.jpg";
import stainlessSteelDoors01 from "@/images/doors/stainless-steel-doors/stainless-steel-doors-01.jpg";
import windowGrills01 from "@/images/doors/window-grills/window-grills-01.jpg";
import windowGrills02 from "@/images/doors/window-grills/window-grills-02.jpg";
import windowGrills03 from "@/images/doors/window-grills/window-grills-03.jpg";
import windowGrills04 from "@/images/doors/window-grills/window-grills-04.jpg";
import windowGrills05 from "@/images/doors/window-grills/window-grills-05.jpg";

export interface GeneratedPhoto {
  src: StaticImageData;
  id: string;
}

export const GENERATED_PHOTOS: Record<string, GeneratedPhoto[]> = {
  "design-doors": [
    { src: designDoors01, id: "design-doors-1" },
    { src: designDoors02, id: "design-doors-2" },
    { src: designDoors03, id: "design-doors-3" },
    { src: designDoors04, id: "design-doors-4" },
    { src: designDoors05, id: "design-doors-5" },
    { src: designDoors06, id: "design-doors-6" },
    { src: designDoors07, id: "design-doors-7" },
  ],
  "diamond-doors": [
    { src: diamondDoors01, id: "diamond-doors-1" },
    { src: diamondDoors02, id: "diamond-doors-2" },
    { src: diamondDoors03, id: "diamond-doors-3" },
    { src: diamondDoors04, id: "diamond-doors-4" },
    { src: diamondDoors05, id: "diamond-doors-5" },
    { src: diamondDoors06, id: "diamond-doors-6" },
    { src: diamondDoors07, id: "diamond-doors-7" },
    { src: diamondDoors08, id: "diamond-doors-8" },
  ],
  "double-doors": [
    { src: doubleDoors01, id: "double-doors-1" },
  ],
  "perforated-mesh": [
    { src: perforatedMesh01, id: "perforated-mesh-1" },
    { src: perforatedMesh02, id: "perforated-mesh-2" },
    { src: perforatedMesh03, id: "perforated-mesh-3" },
  ],
  "privacy-mesh-doors": [
    { src: privacyMeshDoors01, id: "privacy-mesh-doors-1" },
    { src: privacyMeshDoors02, id: "privacy-mesh-doors-2" },
    { src: privacyMeshDoors03, id: "privacy-mesh-doors-3" },
    { src: privacyMeshDoors04, id: "privacy-mesh-doors-4" },
    { src: privacyMeshDoors05, id: "privacy-mesh-doors-5" },
    { src: privacyMeshDoors06, id: "privacy-mesh-doors-6" },
    { src: privacyMeshDoors07, id: "privacy-mesh-doors-7" },
    { src: privacyMeshDoors08, id: "privacy-mesh-doors-8" },
    { src: privacyMeshDoors09, id: "privacy-mesh-doors-9" },
    { src: privacyMeshDoors10, id: "privacy-mesh-doors-10" },
    { src: privacyMeshDoors11, id: "privacy-mesh-doors-11" },
    { src: privacyMeshDoors12, id: "privacy-mesh-doors-12" },
    { src: privacyMeshDoors13, id: "privacy-mesh-doors-13" },
    { src: privacyMeshDoors14, id: "privacy-mesh-doors-14" },
    { src: privacyMeshDoors15, id: "privacy-mesh-doors-15" },
    { src: privacyMeshDoors16, id: "privacy-mesh-doors-16" },
  ],
  "roller-shutters": [
    { src: rollerShutters01, id: "roller-shutters-1" },
    { src: rollerShutters02, id: "roller-shutters-2" },
    { src: rollerShutters03, id: "roller-shutters-3" },
    { src: rollerShutters04, id: "roller-shutters-4" },
    { src: rollerShutters05, id: "roller-shutters-5" },
    { src: rollerShutters06, id: "roller-shutters-6" },
    { src: rollerShutters07, id: "roller-shutters-7" },
    { src: rollerShutters08, id: "roller-shutters-8" },
    { src: rollerShutters09, id: "roller-shutters-9" },
    { src: rollerShutters10, id: "roller-shutters-10" },
    { src: rollerShutters11, id: "roller-shutters-11" },
    { src: rollerShutters12, id: "roller-shutters-12" },
    { src: rollerShutters13, id: "roller-shutters-13" },
    { src: rollerShutters14, id: "roller-shutters-14" },
    { src: rollerShutters15, id: "roller-shutters-15" },
    { src: rollerShutters16, id: "roller-shutters-16" },
    { src: rollerShutters17, id: "roller-shutters-17" },
    { src: rollerShutters18, id: "roller-shutters-18" },
    { src: rollerShutters19, id: "roller-shutters-19" },
    { src: rollerShutters20, id: "roller-shutters-20" },
    { src: rollerShutters21, id: "roller-shutters-21" },
    { src: rollerShutters22, id: "roller-shutters-22" },
    { src: rollerShutters23, id: "roller-shutters-23" },
    { src: rollerShutters24, id: "roller-shutters-24" },
    { src: rollerShutters25, id: "roller-shutters-25" },
    { src: rollerShutters26, id: "roller-shutters-26" },
    { src: rollerShutters27, id: "roller-shutters-27" },
    { src: rollerShutters28, id: "roller-shutters-28" },
    { src: rollerShutters29, id: "roller-shutters-29" },
    { src: rollerShutters30, id: "roller-shutters-30" },
    { src: rollerShutters31, id: "roller-shutters-31" },
    { src: rollerShutters32, id: "roller-shutters-32" },
    { src: rollerShutters33, id: "roller-shutters-33" },
    { src: rollerShutters34, id: "roller-shutters-34" },
    { src: rollerShutters35, id: "roller-shutters-35" },
    { src: rollerShutters36, id: "roller-shutters-36" },
    { src: rollerShutters37, id: "roller-shutters-37" },
    { src: rollerShutters38, id: "roller-shutters-38" },
    { src: rollerShutters39, id: "roller-shutters-39" },
    { src: rollerShutters40, id: "roller-shutters-40" },
    { src: rollerShutters41, id: "roller-shutters-41" },
    { src: rollerShutters42, id: "roller-shutters-42" },
    { src: rollerShutters43, id: "roller-shutters-43" },
    { src: rollerShutters44, id: "roller-shutters-44" },
  ],
  "sliding-doors": [
    { src: slidingDoors01, id: "sliding-doors-1" },
    { src: slidingDoors02, id: "sliding-doors-2" },
    { src: slidingDoors03, id: "sliding-doors-3" },
    { src: slidingDoors04, id: "sliding-doors-4" },
    { src: slidingDoors05, id: "sliding-doors-5" },
    { src: slidingDoors06, id: "sliding-doors-6" },
    { src: slidingDoors07, id: "sliding-doors-7" },
    { src: slidingDoors08, id: "sliding-doors-8" },
    { src: slidingDoors09, id: "sliding-doors-9" },
    { src: slidingDoors10, id: "sliding-doors-10" },
    { src: slidingDoors11, id: "sliding-doors-11" },
    { src: slidingDoors12, id: "sliding-doors-12" },
    { src: slidingDoors13, id: "sliding-doors-13" },
    { src: slidingDoors14, id: "sliding-doors-14" },
    { src: slidingDoors15, id: "sliding-doors-15" },
    { src: slidingDoors16, id: "sliding-doors-16" },
    { src: slidingDoors17, id: "sliding-doors-17" },
    { src: slidingDoors18, id: "sliding-doors-18" },
    { src: slidingDoors19, id: "sliding-doors-19" },
    { src: slidingDoors20, id: "sliding-doors-20" },
  ],
  "stainless-steel-doors": [
    { src: stainlessSteelDoors01, id: "stainless-steel-doors-1" },
  ],
  "window-grills": [
    { src: windowGrills01, id: "window-grills-1" },
    { src: windowGrills02, id: "window-grills-2" },
    { src: windowGrills03, id: "window-grills-3" },
    { src: windowGrills04, id: "window-grills-4" },
    { src: windowGrills05, id: "window-grills-5" },
  ],
};
